version: "3.3" 
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"